function get() {
	return data[Math.floor(Math.random() * data.length)]
}

var data = [
	"Hydrogen is the chemical element with symbol H and atomic number 1.",
	"Hydrogen is the most abundant element in the universe.",
	"Hydrogen is the name of a champion Australian Thoroughbred racehorse.",
	"Hydrogen is the most abundant element in the universe, making up about 75% of its elemental mass.",
	"Hydrogen is estimated that there are about 700 billion stars in the observable universe, and almost all of them are made up of hydrogen.",
	"Hydrogen is the lightest element on the periodic table, with an atomic number of 1.",
	"Hydrogen is highly flammable and can be used as a fuel source for various applications.",
	"Hydrogen is used in the production of ammonia, which is essential for the manufacturing of fertilizers.",
	"Hydrogen is also used in the petroleum refining process to remove impurities from crude oil.",
	"Hydrogen fuel cells are being developed as a clean and sustainable energy source for vehicles.",
	"Hydrogen gas is colorless, odorless, and tasteless.",
	"Hydrogen has the highest energy content per unit of weight of any known fuel.",
	"Hydrogen is a key component of water, making up about 11% of its molecular weight.",
	"Hydrogen was first discovered by the English chemist Henry Cavendish in 1766.",
	'The name "hydrogen" comes from the Greek words "hydro" meaning water and "genes" meaning generator.',
	"In the early 19th century, hydrogen was used in hot air balloons as a lifting gas.",
	"Hydrogen has played a crucial role in space exploration.",
	"Scientists have long recognized the potential of hydrogen as a clean and sustainable energy source.",
	"With an atomic number of 1, hydrogen is the lightest element on the periodic table.",
	"Hydrogen is highly reactive and readily forms compounds with other elements.",
	"Hydrogen gas is colorless, odorless, and tasteless, making it difficult to detect without specialized equipment.",
	"Hydrogen gas has a low density, which allows it to rise in the atmosphere.",
	"Hydrogen has the highest energy content per unit of weight of any known fuel.",
	"Hydrogen plays a significant role in our daily lives, often in ways we may not realize.",
	"Hydrogen is a key component of water, making up about 11% of its molecular weight.",
	"Hydrogen is used in the production of ammonia, which is a crucial component in the manufacturing of fertilizers.",
	"Hydrogen is used in the petroleum refining process to remove impurities from crude oil.",
	"Hydrogen is used in the food processing industry to hydrogenate oils and fats.",
	"Hydrogen is used in the production of metals such as steel and titanium.",
	"Hydrogen has gained significant attention as a potential fuel source for various applications.",
	"Hydrogen fuel cells are devices that convert the chemical energy of hydrogen into electrical energy.",
	"When hydrogen is used in fuel cells, the only byproduct is water.",
	"Hydrogen fuel cell vehicles have a comparable range to conventional gasoline-powered vehicles and can be refueled in a matter of minutes.",
	"One of the main challenges in adopting hydrogen fuel cell technology is the development of a widespread refueling infrastructure.",
	"Hydrogen fuel cells have the potential to power not only cars but also buses, trains, ships, and even buildings.",
	"Hydrogen can be produced using excess renewable energy during times of low demand.",
	"Hydrogen energy storage systems can help balance the electrical grid by providing a reliable source of power during peak demand periods.",
	"Hydrogen has the potential for long-term energy storage, allowing for the utilization of renewable energy sources even when the sun isn't shining or the wind isn't blowing.",
	"While hydrogen offers many benefits, there are also safety considerations and challenges associated with its use.",
	"Hydrogen is highly flammable and can ignite at concentrations as low as 4%.",
	"Due to its colorless and odorless nature, detecting hydrogen leaks can be challenging.",
	"Storing and transporting hydrogen safely is a challenge due to its low density and high reactivity.",
	"The cost of producing hydrogen is currently higher compared to conventional fuels.",
	"Hydrogen has three isotopes: protium, deuterium, and tritium.",
	"Hydrogen isotopes, particularly deuterium and tritium, are used in nuclear fusion reactions to release vast amounts of energy.",
	"Hydrogen can act as a catalyst in various chemical reactions, making it an essential component in many industrial processes.",
	"Hydrogen gas is being studied for its potential therapeutic applications, such as reducing inflammation and oxidative stress in the body.",
	"Scientists are researching new ways to produce hydrogen efficiently and sustainably, as well as exploring its potential as a clean energy carrier.",
	"The future of hydrogen looks promising, with ongoing advancements and potential applications.",
	"Hydrogen fuel cell technology is being tested for use in trains, offering a clean and efficient alternative to diesel-powered locomotives.",
	"Hydrogen is a versatile and fascinating element with numerous applications and potential uses.",
]

