function get() {
	return data[Math.floor(Math.random() * data.length)]
}

var data = [
	'The name "hydrogen" comes from the Greek words ὑδρο- (hydro) meaning water and -γενής (genes) meaning generator.',
	"With an atomic number of 1, hydrogen is the lightest element on the periodic table.",
	"While hydrogen offers many benefits, there are also safety considerations and challenges associated with its use.",
	"When hydrogen is used in fuel cells, the only byproduct is water.",
	"The future of hydrogen looks promising, with ongoing advancements and potential applications.",
	"The first hydrogen-filled balloon was invented by Jacques Charles in 1783.",
	"Storing and transporting hydrogen safely is a challenge due to its low density and high reactivity.",
	"Scientists have long recognized the potential of hydrogen as a clean and sustainable energy source.",
	"Positivaly charged hydrogen, H+, is often called a proton.",
	"Oxidation of hydrogen gives H+, which contains no electrons and a nucleus composed of one proton.",
	"In the early 19th century, hydrogen was used in hot air balloons as a lifting gas.",
	"Hydrogen was first discovered by the English chemist Henry Cavendish in 1766.",
	"Hydrogen plays a significant role in our daily lives, often in ways we may not realize.",
	"Hydrogen isotopes, particularly deuterium and tritium, are used in nuclear fusion reactions.",
	"Hydrogen is used in the production of metals such as steel and titanium.",
	"Hydrogen is used in the production of ammonia, which is essential for the manufacturing of fertilizers.",
	"Hydrogen is used in the petroleum refining process to remove impurities from crude oil.",
	"Hydrogen is used in the food processing industry to hydrogenate oils and fats.",
	"Hydrogen is the most abundant element in the universe, making up about 75% of its elemental mass.",
	"Hydrogen is the most abundant element in the human body in terms of numbers of atoms.",
	"Hydrogen is the third most abundant element in the human body by mass.",
	"Hydrogen is the lightest element on the periodic table, with an atomic number of 1.",
	"Hydrogen is the chemical element with symbol H and atomic number 1.",
	"Hydrogen is highly reactive and readily forms compounds with other elements.",
	"Hydrogen is highly flammable and can ignite at concentrations as low as 4%.",
	"Hydrogen is highly flammable and can be used as a fuel source for various applications.",
	"There are about 700 billion stars in the observable universe, and almost all of them are made up of hydrogen.",
	"Hydrogen is used in the petroleum refining process to remove impurities from crude oil.",
	"Hydrogen is a key component of water, making up about 11% of its molecular weight.",
	"Hydrogen has three isotopes: protium, deuterium, and tritium.",
	"Hydrogen has the highest energy content per unit of weight of any known fuel.",
	"Hydrogen has played a crucial role in space exploration.",
	"Hydrogen has gained significant attention as a potential fuel source for various applications.",
	"Hydrogen gas was first artificially produced in the early 16th century by the reaction of acids on metals",
	"Hydrogen gas is colorless, odorless, and tasteless.",
	"Hydrogen gas is colorless, odorless, and tasteless, making it difficult to detect without specialized equipment.",
	"Hydrogen gas has potential therapeutic applications, such as reducing inflammation and oxidative stress in the body.",
	"Hydrogen gas has a low density, which allows it to rise in the atmosphere.",
	"Hydrogen fuel cells have the potential to power not only cars but also buses, trains, ships, and even buildings.",
	"Hydrogen can be produced using excess renewable energy during times of low demand.",
	"Hydrogen can act as a catalyst in various chemical reactions, making it an essential component in many industrial processes.",
	"Due to its colorless and odorless nature, detecting hydrogen leaks can be challenging.",
	"Hydrogen is the only neutral atom for which the Schrödinger equation can be solved analytically.",
	"The study of the energetics and chemical bonding of hydrogen has played a key role in the development of quantum mechanics.", 
]

